### ISSUE TITLE
help to use the lib

### ISSUE THREAD

**Issue by geohuz** [LucaWolf/des.nim#1]
I'm not able to figure out how to use the triple des lib to encrypt a key, I used pyDes lib and its signature is like:
`encrypt(des3key, modeECB, pad=None, padmode=PKCS5)`

and in the code, I saw sth like:

`desCrypter.encrypt(des.fromHex(...), output, mode)`

I can't see padmode, and pad..., and it seems that under ECB mode, the IV, pad, padmode are all optional

I tried to write the following code:

```
let des3key = "ad6a0456916a4923b5bb91ce"
var
  desCrypter = newDesCipher(des.fromHex(des3key))
  output: seq[byte]

desCrypter.encrypt("", output, modeECB) # No clear key

```

and got the following error:

`
Error: unhandled exception: .nimble/pkgs/des-0.0.11/des/des_api.nim(99, 17) `false` Key not desBlockSize multiple:12 [AssertionError]
`

**Comment by LucaWolf** [comment]
```nim
import strutils, sequtils
import des

# clear key must be multiple of 8 bytes
let clearKey = "0132546798ABCDFE__EFDCBA8976452310__0132546798ABCDFE"
var desCrypter = newDesCipher(des.fromHex(clearKey))
var padBlock: desBlock
var dataEnc: seq[byte]
let dataClear = "this is your ascii input -- or use fromHex(raw_binary)"

# output data must be pre-allocated
let n  = (dataClear.len + 7) div desBlockSize
dataEnc.setlen(n * 8)

# input is only proccesed for multiple of 8 bytes
desCrypter.encrypt(dataClear, dataEnc, modeCBC)

# process the incomplete last block (if any)
if lastBlock(dataClear, padBlock, padPKCS5, false):
    var tmp: desBlock # cannot write directly into slice (openArray incompatible?)
    desCrypter.encrypt(padBlock, tmp, modeCBC)
    dataEnc[^8..^1] = tmp
```

**Comment by LucaWolf** [comment]
```nim
import strutils, sequtils
import des

# clear key must be multiple of 8 bytes
let clearKey = "0123456789ABCDEF__12345678AABBCCDD"
var desCrypter = newDesCipher(des.fromHex(clearKey))
var padBlock: desBlock
var dataEnc: seq[byte]
let dataClear = "this is your ascii input -- or use fromHex(raw_binary)"

# output data must be pre-allocated
let n  = (dataClear.len + 7) div desBlockSize
dataEnc.setlen(n * 8)

# input is only procesed for multiple of 8 bytes
desCrypter.encrypt(dataClear, dataEnc, modeCBC)

# process the incomplete last block (if any)
if lastBlock(dataClear, padBlock, padPKCS5, false):
    var tmp: desBlock # cannot write directly into slice (openArray incompatible?)
    desCrypter.encrypt(padBlock, tmp, modeCBC)
    dataEnc[^8..^1] = tmp
```

**Comment by geohuz** [comment]
I think I'm stuck on the key: "ad6a0456916a4923b5bb91ce", which has length 24, in python we use the 'byte string' so just b"ad6a0456916a4923b5bb91ce", but in nim after fromHex("ad6a0456916a4923b5bb91ce") the length is 12 and that cause the issue. But I don't know how to make it as byte string in nim, do you have any suggestion?

Thanks

**Comment by LucaWolf** [comment]
If I understand you correctly you want to use the key literally as chars array 'a', 'd', '6', etc? 
This seems a bit strange as the listing looks very hex-ascii.
Are you sure your key is not in fact required to be something like byte array 0xad, 0x6a, 0x04, 0x56, etc?

Anyway, for the literal value to be passed into this library API you still need to convert to its binary representation like:
```nim
let clearKeyText = "ad6a0456916a4923b5bb91ce"
var clearKeyBytes = newSeq[byte](clearKeyText.len)

clearKeyText.copyto(clearKeyBytes)

echo $clearKeyBytes
# @[97, 100, 54, 97, 48, 52, 53, 54, 
#   57, 49, 54, 97, 52, 57, 50, 51,
#   98, 53, 98, 98, 57, 49, 99, 101] <-- these are decimal values
# e.g. 97 = 0x61 representing 'a' in ASCII encoding
```

**Comment by geohuz** [comment]
@LucaWolf , thanks a lot! That solves my issue!!
